import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import ClientWrapper from "./client-wrapper";

const outfit = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${outfit.className} dark:bg-gray-900`}>
        <ClientWrapper>{children}</ClientWrapper>
      </body>
    </html>
  );
}
